# The overrides in this file are for **development only**!

services:
  test_conf_nginx:
    volumes:
      - ./container/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf

  test_conf_frontend:
    build:
      args:
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
    volumes:
      - ./container/dev/vite/vite.config.ts:/app/vite.config.ts # Vite configuration that supports hot reloading.
      - ./frontend:/app # The frontend code.
      - /app/node_modules # This is needed to ensure that the node_modules directory is not overwritten by the host.
      - /app/.svelte-kit
    environment:
      - PUBLIC_API_BASE_URL_SSR=http://test_conf_backend
      - PUBLIC_API_BASE_URL_CSR=http://localhost/api

  test_conf_backend:
    build:
      args:
          HOST_UID: ${HOST_UID:-1000}
          HOST_GID: ${HOST_GID:-1000}
    volumes:
      - ./container/dev/.env:/var/www/html/.env # Environment file for CodeIgniter4 configuration.
      - ./container/dev/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf # Apache config to configure CORS.
      - ./container/dev/apache/ports.conf:/etc/apache2/ports.conf # Apache main config (to change the port if necessary).
      - ./backend:/var/www/html # The backend code.
    depends_on:
      - test_conf_mail

  test_conf_mail:
    container_name: test_conf_mail
    image: changemakerstudiosus/papercut-smtp:latest
    restart: unless-stopped
    ports:
      - "8080:80"

  test_conf_phpmyadmin:
    container_name: test_conf_phpmyadmin
    image: phpmyadmin:5.2.2-apache
    restart: unless-stopped
    environment:
      - PMA_HOST=test_conf_db
      - PMA_USER=test_conf_user
      - PMA_PASSWORD=1234

  test_conf_db:
    ports:
      - "3306:3306" # Make database accessible from the host (e.g. to connect using JetBrains DataGrip).
    env_file: ./container/dev/.compose_env # This file includes the database configuration env variables.
