FROM php:8.2-apache-bookworm

RUN apt-get -y update \
    && apt-get install -y libicu-dev \
    && docker-php-ext-configure intl \
    && docker-php-ext-install intl \
    && rm -rf /var/cache/apt/archives /var/lib/apt/lists/*
RUN apt-get -y update \
    && apt-get install -y default-libmysqlclient-dev \
    && docker-php-ext-configure mysqli \
    && docker-php-ext-install mysqli \
    && rm -rf /var/cache/apt/archives /var/lib/apt/lists/*
RUN apt-get -y update \
    && apt-get install -y libzip-dev unzip \
    && docker-php-ext-configure zip \
    && docker-php-ext-install zip \
    && rm -rf /var/cache/apt/archives /var/lib/apt/lists/*

COPY install-composer.sh /root/install-composer.sh
RUN /root/install-composer.sh

COPY app-host.conf /etc/apache2/conf-available/app-host.conf
RUN cd /etc/apache2/conf-enabled/ && ln -s ../conf-available/app-host.conf app-host.conf
RUN cd /etc/apache2/mods-enabled/ \
    && ln -s ../mods-available/proxy.load proxy.load \
    && ln -s ../mods-available/proxy.conf proxy.conf \
    && ln -s ../mods-available/proxy_http.load proxy_http.load \
    && ln -s ../mods-available/proxy_wstunnel.load proxy_wstunnel.load \
    && ln -s ../mods-available/headers.load headers.load \
    && ln -s ../mods-available/rewrite.load rewrite.load 
RUN ls -la /etc/apache2/mods-enabled/ && apachectl configtest

RUN mkdir -p backend
COPY website-backend/composer.* backend/
RUN composer -d backend install

COPY website-backend/ backend/
COPY website-frontend/static/favicon.ico default/index.php /var/www/html/

RUN apt-get -y update && apt-get install -y default-mysql-client && rm -rf /var/cache/apt/archives /var/lib/apt/lists/*
