services:
  test_conf_nginx:
    image: nginx:1.26.3-bookworm
    container_name: test_conf_nginx
    ports:
      - "8082:80"
    volumes:
      - ./.container/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - test_conf_frontend
      - test_conf_backend

  test_conf_frontend:
    image: ghcr.io/techstreamconference/website-frontend:nightly
    container_name: test_conf_frontend
    ports:
      - "8081:3000" # Port 8080 (host) maps to port 3000 (container).
    environment:
      - PUBLIC_API_BASE_URL_SSR=http://test_conf_backend:80
      - PUBLIC_API_BASE_URL_CSR=http://localhost:8082/api
    depends_on:
      - test_conf_backend

  test_conf_backend:
    image: ghcr.io/techstreamconference/website-backend:v0.1.0
    container_name: test_conf_backend
    ports:
      - "8080:80"
    volumes:
      - ./data/uploads:/var/www/html/writable/uploads # For file uploads.
      - ./.container/index.html:/var/www/html/writable/uploads/index.html # File that prevents direct directory access.
      - ./.env:/var/www/html/.env # Environment file for CodeIgniter4 configuration.
      - ./.container/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf # Apache config to configure CORS.
      - ./.container/apache/ports.conf:/etc/apache2/ports.conf # Apache main config (to change the port if necessary).
    depends_on:
      - test_conf_db # Ensure 'test_conf_db' service starts before 'test_conf_app'

  test_conf_db:
    image: mariadb:11.4.5
    container_name: test_conf_db
    env_file: .compose_env # This file includes the database configuration env variables.
    ports:
      - "3306:3306"
    volumes:
      - ./data/database:/var/lib/mysql
